theme: jekyll-theme-minimal
title: Ruvari
description: Ruvari is a woman-owned, ethical jewelry maker that specializes in lab-grown diamonds. Stay tuned to this site for an e-commerce store.
github:
  is_project_page: false